# Generated by Django 5.0.7 on 2025-04-17 06:17

import criminal_rec.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('camera_source', models.CharField(max_length=255)),
                ('threshold', models.FloatField(default=0.8)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('criminal_photo', models.ImageField(blank=True, null=True, upload_to=criminal_rec.models.upload_to_front)),
                ('captured_image', models.ImageField(blank=True, null=True, upload_to='captured_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('scars_or_marks', models.TextField(blank=True, null=True)),
                ('crimes_committed', models.TextField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorized', models.BooleanField(default=True)),
            ],
        ),
    ]
