# Generated by Django 5.0.7 on 2025-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_rec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminalrec',
            old_name='name',
            new_name='criminal_name',
        ),
        migrations.AlterField(
            model_name='criminalrec',
            name='criminal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='front/'),
        ),
    ]
