# Generated by Django 5.0.7 on 2025-04-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_rec', '0002_rename_name_criminalrec_criminal_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminalrec',
            old_name='crimes_committed',
            new_name='crime',
        ),
    ]
