# Generated by Django 5.0.7 on 2025-04-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_rec', '0003_rename_crimes_committed_criminalrec_crime'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrec',
            name='parent_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='criminalrec',
            name='parole_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
