# Generated by Django 5.2 on 2025-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_rec', '0004_criminalrec_parent_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalrec',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
